### ISSUE TITLE
Suggested Summary & Objectives

### ISSUE THREAD

**Issue by walwoodr** [learn-co-curriculum/orm-video-review-orms-and-sql-joins#1]
**Summary**
Combine your knowledge of object relationships in object oriented ruby and your knowledge of join tables in SQL in order to write ORM-based methods that will allow you to create related objects from related SQLite3 databases. 

**Objectives**
- Understand how database domain models relate with object oriented domain models. 
- Understand how SQL foreign keys and join tables can be used to represent object relationships.   
- Create objects with a belongs to relationship from database tables representing a belongs to relationship. 
- Create objects with a has many relationship from tables representing a has many relationship  
- Use SQL join queries to create objects with a has many through relationship from join tables.

**Comment by gj** [comment]
Merged in — thanks @walwoodr !
