### ISSUE TITLE
Suggestion: Place video in a different portion of curriculum

### ISSUE THREAD

**Issue by walwoodr** [learn-co-curriculum/orm-video-review-orms-and-sql-joins#2]
I'd suggest placing this before the introduction to Dynamic ORMs or perhaps after the Dynamic ORMs with Inheritance lab. Primary reason: three 1.5 hour long videos in a row are *excruciating* to get through. But also because this video covers the introductory ORM topic area.

**Comment by gj** [comment]
Moved it after the Dynamic ORMs with Inheritance Lab. Thanks @walwoodr !
