### ISSUE TITLE
Correct usage for DISTINCT keyword

### ISSUE THREAD

**Issue by AbhishekChd** [learn-co-curriculum/orm-video-review-orms-and-sql-joins#4]
In the video at [01:21:09](https://www.youtube.com/watch?time_continue=4860&v=mZROu5oSWfI) the DISTINCT keyword was used on id column, then all columns were accessed again,
```sql
SELECT DISTINCT(customers.id), customer.*  FROM customers
INNER JOIN carts on customers.id = carts.customer_id
INNER JOIN line_items on carts.id = line_items.cart_id
WHERE line_items.product_id = 1;
```
I think, the correct usage would be to use it on all rows to reduce repition,
```sql
SELECT DISTINCT customers.* FROM customers
INNER JOIN carts on customers.id = carts.customer_id
INNER JOIN line_items on carts.id = line_items.cart_id
WHERE line_items.product_id = 1;
```

**Comment by curiositypaths** [comment]
Thank you for bringing this to our attention. We will review the code when we update the video.

As always thank you for contributing.
