### ISSUE TITLE
Consider editing the video

### ISSUE THREAD

**Issue by sjmoody** [learn-co-curriculum/orm-video-review-orms-and-sql-joins#6]
There is a five minute dead space around 51:00 in the video.  Please consider editing the video to remove this.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#7.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
